services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
      target: base
    ports:
      - "3000:3000"
    environment:
      - USE_MOCK=${USE_MOCK:-true}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - MISTRAL_MODEL=${MISTRAL_MODEL:-mistral-small-latest}
      - TEMPERATURE_DEFAULT=${TEMPERATURE_DEFAULT:-0.2}
    command: ["pnpm", "dev"]
    restart: unless-stopped
