version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    command: pnpm dev
    # Enable if file watching requires polling (e.g., some macOS setups)
    # environment:
    #   CHOKIDAR_USEPOLLING: "1"
