services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
      target: base
    ports:
      - "3000:3000"
    volumes:
      - ./web/.env:/app/web/.env:ro
    command: ["pnpm", "dev"]
    restart: unless-stopped
