FROM node:22-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY web/pnpm-lock.yaml web/package.json ./

RUN pnpm install --frozen-lockfile

COPY web .

RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start"]
